function sceneLabelMap = sceneLabelMap()
sceneLabelMap = zeros(150,1);
sceneLabelMap(1) = 1; % (wall) indoor
sceneLabelMap(2) = 2; % (building) building
sceneLabelMap(3) = 3; % (sky) sky
sceneLabelMap(4) = 4; % (floor) floor
sceneLabelMap(5) = 5; % (tree) plant
sceneLabelMap(6) = 1; % (ceiling) indoor
sceneLabelMap(7) = 6; % (road) road
sceneLabelMap(8) = 1; % (bed) indoor
sceneLabelMap(9) = 2; % (windowpane) building
sceneLabelMap(10) = 5; % (grass) plant
sceneLabelMap(11) = 1; % (cabninet) indoor
sceneLabelMap(12) = 7; % (sidewalk) sidewalk
sceneLabelMap(13) = 8; % (person) person
sceneLabelMap(14) = 4; % (earth) floor
sceneLabelMap(15) = 2; % (door) building
sceneLabelMap(16) = 1; % (table) indoor
sceneLabelMap(17) = 3; % (mountain) sky
sceneLabelMap(18) = 5; % (plant) plant
sceneLabelMap(19) = 1; % (curtain) indoor
sceneLabelMap(20) = 1; % (chair) indoor
sceneLabelMap(21) = 9; % (car) vehicle
sceneLabelMap(22) = 10; % (water) water
sceneLabelMap(23) = 2; % (painting) building
sceneLabelMap(24) = 1; % (sofa) indoor
sceneLabelMap(25) = 1; % (shelf) indoor
sceneLabelMap(26) = 2; % (house) building
sceneLabelMap(27) = 10; % (sea) water
sceneLabelMap(28) = 1; % (mirror) water
sceneLabelMap(29) = 1; % (rug) water
sceneLabelMap(30) = 4; % (feild) floor
sceneLabelMap(31) = 1; % (armchair) indoor
sceneLabelMap(32) = 1; % (seat) indoor
sceneLabelMap(33) = 7; % (fence) sidewalk
sceneLabelMap(34) = 1; % (dest) indoor
sceneLabelMap(35) = 4; % (rock) floor
sceneLabelMap(36) = 1; % (wardrobe) indoor
sceneLabelMap(37) = 1; % (lamp) indoor
sceneLabelMap(38) = 1; % (bathtub) indoor
sceneLabelMap(39) = 7; % (railing) sidewalk
sceneLabelMap(40) = 1; % (cution) indoor
sceneLabelMap(41) = 2; % (base) building
sceneLabelMap(42) = 1; % (box) indoor
sceneLabelMap(43) = 7; % (column) sidewalk
sceneLabelMap(44) = 11; % (signboard) sign
sceneLabelMap(45) = 1; % (chest of drawers) indoor
sceneLabelMap(46) = 1; % (counter) indoor
sceneLabelMap(47) = 4; % (sand) floor
sceneLabelMap(48) = 10; % (sink) water
sceneLabelMap(49) = 2; % (skycraper) building
sceneLabelMap(50) = 1; % (fireplace) indoor
sceneLabelMap(51) = 1; % (refrigerator) indoor
sceneLabelMap(52) = 7; % (grandstand) sidewalk
sceneLabelMap(53) = 7; % (path) sidewalk
sceneLabelMap(54) = 7; % (stairs) sidewalk
sceneLabelMap(55) = 4; % (ranway) floor
sceneLabelMap(56) = 1; % (case) indoor
sceneLabelMap(57) = 1; % (pool table) indoor
sceneLabelMap(58) = 1; % (pillow) indoor
sceneLabelMap(59) = 1; % (screen door) indoor
sceneLabelMap(60) = 7; % (stairway) sidewalk
sceneLabelMap(61) = 10; % (river) water
sceneLabelMap(62) = 7; % (bridge) sidewalk
sceneLabelMap(63) = 1; % (bookcase) indoor
sceneLabelMap(64) = 1; % (blind) indoor
sceneLabelMap(65) = 1; % (caffe table) indoor
sceneLabelMap(66) = 1; % (toilet) indoor
sceneLabelMap(67) = 5; % (flower) plant
sceneLabelMap(68) = 1; % (book) indoor
sceneLabelMap(69) = 1; % (hill) floor
sceneLabelMap(70) = 1; % (bench) indoor
sceneLabelMap(71) = 1; % (countertop) indoor
sceneLabelMap(72) = 1; % (stove) indoor
sceneLabelMap(73) = 5; % (palm) plant
sceneLabelMap(74) = 1; % (ktichen island) indoor
sceneLabelMap(75) = 1; % (computer) indoor
sceneLabelMap(76) = 1; % (swival chair) indoor
sceneLabelMap(77) = 10; % (boat) water
sceneLabelMap(78) = 1; % (bar) indoor
sceneLabelMap(79) = 1; % (arcade mechine) indoor
sceneLabelMap(80) = 2; % (hovel) building
sceneLabelMap(81) = 9; % (bus) vehicle
sceneLabelMap(80) = 1; % (towel) indoor
sceneLabelMap(83) = 1; % (light) indoor
sceneLabelMap(84) = 9; % (truck) vehicle
sceneLabelMap(85) = 2; % (tower) building
sceneLabelMap(86) = 1; % (chandelier) indoor
sceneLabelMap(87) = 2; % (awning) building
sceneLabelMap(88) = 7; % (streetlight) sidewalk
sceneLabelMap(89) = 2; % (booth) building
sceneLabelMap(90) = 1; % (television) receiver
sceneLabelMap(91) = 9; % (airplane) vehicle
sceneLabelMap(92) = 4; % (dirt track) floor
sceneLabelMap(93) = 1; % (apparel) indoor
sceneLabelMap(94) = 7; % (pole) sidewalk
sceneLabelMap(95) = 4; % (land) floor
sceneLabelMap(96) = 7; % (bannister) sidewalk
sceneLabelMap(97) = 7; % (escalator) sidewalk
sceneLabelMap(98) = 1; % (ottoman) indoor
sceneLabelMap(99) = 1; % (bottle) indoor
sceneLabelMap(100) = 1; % (buffet) indoor
sceneLabelMap(101) = 11; % (poster) sign
sceneLabelMap(102) = 1; % (stage) indoor
sceneLabelMap(103) = 9; % (van) vehicle
sceneLabelMap(104) = 9; % (ship) vehicle
sceneLabelMap(105) = 10; % (fountain) water
sceneLabelMap(106) = 1; % (conveyer belt) indoor
sceneLabelMap(107) = 1; % (canopy) indoor
sceneLabelMap(108) = 1; % (washer) indoor
sceneLabelMap(109) = 1; % (plaything) indoor
sceneLabelMap(110) = 10; % (swimming pool) water
sceneLabelMap(111) = 1; % (stool) indoor
sceneLabelMap(112) = 1; % (barrel) indoor
sceneLabelMap(113) = 1; % (basket) indoor
sceneLabelMap(114) = 10; % (waterfall) water
sceneLabelMap(115) = 2; % (tent) building
sceneLabelMap(116) = 1; % (bag) indoor
sceneLabelMap(117) = 9; % (minibike) vehicle
sceneLabelMap(118) = 1; % (cradle) indoor
sceneLabelMap(119) = 1; % (oven) indoor
sceneLabelMap(120) = 1; % (ball) indoor
sceneLabelMap(121) = 1; % (food) indoor
sceneLabelMap(122) = 7; % (step) sidewalk
sceneLabelMap(123) = 9; % (tank) vehicle
sceneLabelMap(124) = 11; % (trade name) sign
sceneLabelMap(125) = 1; % (microwave) indoor
sceneLabelMap(126) = 1; % (pot) indoor
sceneLabelMap(127) = 4; % (animal) floor
sceneLabelMap(128) = 9; % (bicycle) vehicle
sceneLabelMap(129) = 10; % (lake) water
sceneLabelMap(130) = 1; % (dishwasher) indoor
sceneLabelMap(131) = 2; % (screen) building
sceneLabelMap(132) = 1; % (blanket) indoor
sceneLabelMap(133) = 2; % (sculpture) building
sceneLabelMap(134) = 2; % (hood) building
sceneLabelMap(135) = 1; % (sconce) indoor
sceneLabelMap(136) = 1; % (vase) indoor
sceneLabelMap(137) = 11; % (traffic light) sign
sceneLabelMap(138) = 1; % (tray) indoor
sceneLabelMap(139) = 7; % (ashcan) sidewalk
sceneLabelMap(140) = 1; % (fan) indoor
sceneLabelMap(141) = 2; % (pier) building
sceneLabelMap(142) = 2; % (crt screen) building
sceneLabelMap(143) = 1; % (plate) indoor
sceneLabelMap(144) = 7; % (monitor) sidewalk
sceneLabelMap(145) = 11; % (bulletin board) sign
sceneLabelMap(146) = 1; % (shower) indoor
sceneLabelMap(147) = 1; % (radiator) indoor
sceneLabelMap(148) = 2; % (glass) building
sceneLabelMap(149) = 1; % (clock) indoor
sceneLabelMap(150) = 11; % (flag) sign
